# Generated by Django 5.1.7 on 2025-03-26 01:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Admin', max_length=100)),
                ('apellido', models.CharField(default='Sistema', max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('rol', models.CharField(default='Administrador', max_length=50)),
                ('contraseña', models.CharField(default='', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Desconocido', max_length=100)),
                ('apellido', models.CharField(default='Desconocido', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=10)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, default='', null=True)),
                ('institucion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('tipo_institucion', models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada')], default='Pública', max_length=20)),
                ('grado', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_examen', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(default='General', max_length=50)),
                ('duracion', models.IntegerField(default=2)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='General', max_length=100)),
                ('area', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Desconocido', max_length=100)),
                ('apellido', models.CharField(default='Desconocido', max_length=100)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, default='', null=True)),
                ('area_especializacion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('institucion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('Opción Múltiple', 'Opción Múltiple'), ('Verdadero/Falso', 'Verdadero/Falso')], default='Opción Múltiple', max_length=50)),
                ('respuestas_posibles', models.JSONField(default=dict)),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.examen')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_seleccionada', models.CharField(max_length=255)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_global', models.IntegerField(default=0)),
                ('lectura_critica', models.IntegerField(default=0)),
                ('matematicas', models.IntegerField(default=0)),
                ('sociales_ciudadanas', models.IntegerField(default=0)),
                ('ciencias_naturales', models.IntegerField(default=0)),
                ('ingles', models.IntegerField(default=0)),
                ('fecha_resultado', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.estudiante')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.examen')),
            ],
        ),
    ]
