# Generated by Django 5.1.7 on 2025-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contraseña',
            field=models.CharField(default='', max_length=128),
        ),
    ]
