# Generated by Django 5.1.7 on 2025-05-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_estudiante_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='contraseña',
            field=models.CharField(default='1234', max_length=128),
        ),
    ]
