# Generated by Django 5.1.7 on 2025-05-08 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profesor_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='base.profesor'),
            preserve_default=False,
        ),
    ]
