# Generated by Django 5.1.7 on 2025-05-09 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_examen_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='base.profesor'),
        ),
    ]
