# Generated by Django 5.1.7 on 2025-05-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_examen_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='grados',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
