# Generated by Django 5.1.7 on 2025-05-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profesor_grados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='grados',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
