# Generated by Django 5.1.7 on 2025-06-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profesor_grados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='grados',
            field=models.CharField(blank=True, help_text='Grados que enseña, formato: ,9A,9B,10A,', max_length=100, null=True),
        ),
    ]
